
Brand.create(name: "Bud Light", youtubeteaser_link:"https://www.youtube.com/watch?v=ffXmQhrjWV8", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Bud%20Light&window=d",facebook_link: "https://www.facebook.com/BudLight", spots: 3 )
Brand.create(name: "Budweiser", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Budweiser&window=d",facebook_link: "https://www.facebook.com/BudweiserUSA", spots: 1)
Brand.create(name: "Audi", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Audi&window=d",facebook_link: "https://www.facebook.com/audi", spots: 1, seconds: 60)
Brand.create(name: "Axe", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Axe&window=d",facebook_link: "https://www.facebook.com/Axe", spots: 1, seconds: 30)
Brand.create(name: "Butterfinger", youtubeteaser_link:"http://www.youtube.com/watch?v=tnC4vhEiEf4&list=UUHmv_qppzANOXgFb_GoDRmw&feature=share", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Butterfinger&window=d",facebook_link: "https://www.facebook.com/butterfinger", spots: 1, seconds: 30)
Brand.create(name: "Cheerios", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Cheerios&window=d",facebook_link: "https://www.facebook.com/Cheerios", spots: 1)
Brand.create(name: "Chevrolet", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Chevrolet&window=d",facebook_link: "https://www.facebook.com/chevrolet")
Brand.create(name: "Chobani", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Chobani&window=d",facebook_link: "https://www.facebook.com/Chobani", spots: 1, seconds:30)
Brand.create(name: "Coca-Cola", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Coca-cola&window=d",facebook_link: "https://www.facebook.com/cocacola")
Brand.create(name: "Doritos", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Doritos&window=d",facebook_link: "https://www.facebook.com/doritos", spots: 2, seconds:60)
Brand.create(name: "GoDaddy", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=GoDaddy&window=d",facebook_link: "https://www.facebook.com/GoDaddy", spots: 2, seconds:60)
Brand.create(name: "H&M", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=%22H%26M%22&window=d",facebook_link: "https://www.facebook.com/hm", spots: 1, seconds:30)
Brand.create(name: "Heinz Ketchup", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Heinz%20Ketchup&window=d",facebook_link: "https://www.facebook.com/HeinzKetchup", spots: 1, seconds:30)
Brand.create(name: "Hyundai", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Hyundai&window=d",facebook_link: "https://www.facebook.com/Hyundai", spots: 2)

Brand.create(name: "Intuit", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Intuit&window=d",facebook_link: "https://www.facebook.com/intuit", spots: 1, seconds:30)
Brand.create(name: "Turbotax", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=TurboTax&window=d",facebook_link: "https://www.facebook.com/turbotax", spots: 1, seconds:60)
Brand.create(name: "Jaguar", youtubeteaser_link:"http://youtu.be/RWBaF077yWI", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Jaguar&window=d",facebook_link: "https://www.facebook.com/Jaguar", spots: 1, seconds:60)
Brand.create(name: "Kiamotorsworldwide", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Kia&window=d",facebook_link: "https://www.facebook.com/Kiamotorsworldwide")
Brand.create(name: "M&Ms", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=M%26M&window=d",facebook_link: "https://www.facebook.com/mms", spots: 1, seconds:30)


Brand.create(name: "Dannon", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Okios&window=d",facebook_link: "https://www.facebook.com/dannon", spots: 1, seconds:30)
Brand.create(name: "AgeofextinctionMovie", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Transformers&window=d",facebook_link: "https://www.facebook.com/AgeofextinctionMovie", spots: 1, seconds:30)
Brand.create(name: "PepsiUS", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Pepsi&window=d",facebook_link: "https://www.facebook.com/PepsiUS", spots: 2, seconds:60)
Brand.create(name: "SodaStream", youtubeteaser_link:"http://youtu.be/IxB_gduT1wM", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=SodaStream&window=d",facebook_link: "https://www.facebook.com/SodaStream", spots: 1, seconds:30)
Brand.create(name: "Squarespace", youtubeteaser_link:"http://youtu.be/ksXQG-rLjZo", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=SquareSpace&window=d",facebook_link: "https://www.facebook.com/squarespace", spots: 1, seconds:30)
Brand.create(name: "Toyota", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Toyota&window=d",facebook_link: "https://www.facebook.com/toyota", spots: 1, seconds:60)
Brand.create(name: "Volkswagen", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Volkswagen&window=d",facebook_link: "https://www.facebook.com/volkswagen", spots: 1, seconds:60)
Brand.create(name: "Wonderfulpistachios", youtubeteaser_link:"", youtubecommercial_link: "", topsy_link:"http://topsy.com/s?q=Pistachios&window=d",facebook_link: "https://www.facebook.com/wonderfulpistachios", spots: 2, seconds:30)
